name: CI
on:
  pull_request:
    branches: [ "main" ]
    types:
      - closed    
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install -g hasura-cli
      - run: echo ${{secret.HASURA_GRAPHQL_ENDPOINT}}
      - run: echo ${{secret.$HASURA_GRAPHQL_ADMIN_SECRET}}
      - run: hasura deploy --endpoint https://included-tah-83-prod.hasura.app --admin-secret bOruXx13rna5ix5lKoPu2yLZvfX7iiRym4yQRc77gJHUyRCBwKF68pl1AGEGNFiK .
